name: hognaverm
description: >
  Hognaverm: Harusame's Binary Encryption Method
author: Haruka Sato <as.he.that.doth.serve@gmail.com>
homepage: https://halka9000stg.github.io/Hognaverm/
repository: https://github.com/halka9000stg/Hognaverm
version: 0.1.0

environment:
  sdk: ^3.10.1

dependencies:

dev_dependencies:
  # lints: ^6.0.0
  # test: ^1.25.6

topics: